name: Release

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions: {}

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]' && github.event.pull_request.head.ref == 'ci/next-release'
    runs-on: ubuntu-latest
    concurrency:
      group: release
    permissions:
      contents: write
      packages: write
    timeout-minutes: 10
    steps:
      - name: ğŸ›’ Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@conetecdataservices"

        # While there aren't multiple packages to worry about, just change the CWD to simplify things
      - name: ğŸ“¦ Install Dependencies
        run: npm ci

      - name: ğŸ—ï¸ Build & Test
        run: |
          npm run build

      - name: ğŸš¢ Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ·ï¸ Get Tag from package.json
        run: echo "TAG_NAME=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: ğŸ·ï¸ Create Tag
        run: |
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"